package it.redhat.demo.entity;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;

import org.drools.persistence.jpa.marshaller.VariableEntity;

/**
 * This class was automatically generated by the data modeler tool.
 */

@Entity
public class Employee extends VariableEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8778840765450275959L;
	
	private String name;
	private String address;

	@Id
	@GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "EMPLOYEE_ID_GENERATOR")
	@SequenceGenerator(sequenceName = "EMPLOYEE_ID_SEQ", name = "EMPLOYEE_ID_GENERATOR")
	private Long id;

	public Employee() {
	}
	
	public Employee(String name, String address) {
		this.name = name;
		this.address = address;
	}
	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Override
	public String toString() {
		return "Employee [name=" + name + ", address=" + address + "]";
	}

}